import Head from 'next/head'
import Link from 'next/link'
import Header from '../Components/Header'


export default function Home() {
  return (
    <div className='font-sans'>
      <Head>
        <title>Save Space</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>

        <link rel="preconnect" href="https://fonts.gstatic.com" />

        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"></link>
      </Head>
      
      <Header/>

      <HeroSection/>
      
    </ div>
  )
}


function HeroSection () {


  return (
    <div className='max-w-7xl mx-[120px] px-4 sm:px-6'>
      <div className='md:flex items-center space-x-14 py-14'>
          <div className='md:w-1/2'>
            <h1 className='text-[42px] font-bold text-slate-900'>
              <span className=''>
                You Don't Save,
                 <span class="ml-1 before:block before:absolute before:-inset-1 custom-skew before:bg-brand-500 relative inline-block">
                  <span class="relative text-white">We Save!</span>
                </span>
              </span>
              <span className='block mt-2'>Your Money, Your Terms.</span>
            </h1>

            <p className='text-brand-gray text-lg leading-7'>Disrupting the traditional financial sector by offering better financial solutions, while staying true to the human values of trust, honesty, and fairness. Secure your future with our secure investments.</p>

            <Link href="/" className='inline-flex items-center mt-6 py-4 px-6 bg-brand-500 text-white font-bold text-lg rounded-lg hover:bg-blue-700'>Create free account</Link>

            <div className='mt-12 flex items-center space-x-4'>
                <Link href="/" className='inline-flex items-center mt-6 py-4 px-6 border border-brand-500 text-brand-500 font-bold text-lg rounded-lg hover:bg-blue-50'>
                  <svg className='mr-2' xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none"><path fill="#1E1E1E" d="M17.517 12.556c-.01-1.599.715-2.804 2.178-3.692-.818-1.172-2.056-1.816-3.687-1.94-1.545-.122-3.235.9-3.853.9-.654 0-2.15-.858-3.326-.858C6.4 7.003 3.82 8.902 3.82 12.764c0 1.142.209 2.32.626 3.534.558 1.599 2.569 5.515 4.667 5.452 1.096-.026 1.872-.778 3.3-.778 1.385 0 2.102.778 3.325.778 2.117-.03 3.935-3.59 4.465-5.194-2.838-1.338-2.686-3.919-2.686-4Zm-2.463-7.149c1.188-1.41 1.08-2.695 1.045-3.157-1.05.06-2.264.715-2.955 1.519-.762.862-1.21 1.929-1.114 3.131 1.135.087 2.17-.497 3.024-1.493Z"/></svg>
                  Get On Apple
                  </Link>
                <Link href="/" className='inline-flex items-center mt-6 py-4 px-6 border border-brand-500 text-brand-500 font-bold text-lg rounded-lg hover:bg-blue-50'>
                  <svg className='mr-2' xmlns="http://www.w3.org/2000/svg" width="25" height="24" fill="none"><g clip-path="url(#a)"><path fill="#32BBFF" d="M18.423 8.232C15.635 6.672 11.16 4.17 4.22.282A1.673 1.673 0 0 0 2.748.09L14.656 12l3.767-3.767Z"/><path fill="#32BBFF" d="M2.748.09a1.675 1.675 0 0 0-1.144 1.597V22.31a1.674 1.674 0 0 0 1.144 1.598l11.908-11.91L2.748.09ZM14.657 11.999 2.748 23.908a1.656 1.656 0 0 0 1.472-.193c6.731-3.769 11.155-6.243 13.976-7.816l.231-.13-3.77-3.77Z"/><path fill="#2C9FD9" d="M1.604 11.999v10.312a1.674 1.674 0 0 0 1.144 1.597l11.908-11.909H1.604Z"/><path fill="#29CC5E" d="M4.22.283A1.679 1.679 0 0 0 2.495.199l11.981 11.98 3.947-3.947C15.637 6.673 11.162 4.17 4.22.282Z"/><path fill="#D93F21" d="m14.476 11.819-11.98 11.98a1.667 1.667 0 0 0 1.724-.083 9959.34 9959.34 0 0 1 13.976-7.817l.231-.13-3.95-3.95Z"/><path fill="#FFD500" d="M23.397 11.999a1.67 1.67 0 0 0-.86-1.468s-1.069-.596-4.345-2.428l-3.896 3.896 3.9 3.9c3.24-1.819 4.34-2.432 4.34-2.432.572-.32.86-.897.86-1.468Z"/><path fill="#FA0" d="M22.537 13.467c.571-.32.86-.897.86-1.468h-9.101l3.9 3.9c3.24-1.819 4.34-2.432 4.34-2.432Z"/></g><defs><clipPath id="a"><path fill="#fff" d="M.5 0h24v24H.5z"/></clipPath></defs></svg>
                  Get On Android
                  </Link>
            </div>
          </div>

          <div className='md:w-1/2'>
            <div className='relative'>
                <img className='h-[656px] w-auto object-cover' src="/girl-smilling.png" alt="girl-smilling" />
    
                <div className='absolute bottom-0 z-[-1] left-0 h-[523px] w-[478px] bg-brand-500 rounded-2xl'></div>
                <div className='absolute right-0 bottom-[52px] w-[438px] h-[424px] bg-brand-700 rounded-2xl z-[-2]'></div>
              
            </div>
            
          </div>
          
      </div>
    </div>
  )
}